
CREATE TABLE E (FromEtoC VARCHAR(255) FOREIGN KEY REFERENCES C(VALUE) NULL)
;
CREATE TABLE D (id VARCHAR(255) PRIMARY KEY, def INT(31) NULL)
;
CREATE TABLE FromDtoB
(D_id VARCHAR(255) FOREIGN KEY REFERENCES D(ID), B_id VARCHAR(255) FOREIGN KEY REFERENCES B(ID), CONSTRAINT FromDtoB_pkey PRIMARY KEY(D_ID, B_ID))
;
CREATE TABLE C VALUE VARCHAR(255) PRIMARY KEY
;
INSERT INTO C
VALUES (Individual3, individual2, individual1)
;
CREATE TABLE B (FromEtoC VARCHAR(255) FOREIGN KEY REFERENCES C(VALUE) NULL, FromAtoC VARCHAR(255) FOREIGN KEY REFERENCES C(VALUE) NOT NULL, id VARCHAR(255) PRIMARY KEY, FromBtoDButSomehowDifferent VARCHAR(255) FOREIGN KEY REFERENCES D(ID) NOT NULL, FromBtoD VARCHAR(255) FOREIGN KEY REFERENCES D(ID) NULL)
;
CREATE TABLE abc
(B_id VARCHAR(255) FOREIGN KEY REFERENCES B(ID), value DATETIME, CONSTRAINT abc_pkey PRIMARY KEY(B_ID, VALUE))
;
CREATE TABLE bcd
(B_id VARCHAR(255) FOREIGN KEY REFERENCES B(ID), value DOUBLE(63, 6), CONSTRAINT bcd_pkey PRIMARY KEY(B_ID, VALUE))
;
CREATE TABLE A (FromEtoC VARCHAR(255) FOREIGN KEY REFERENCES C(VALUE) NULL, FromAtoC VARCHAR(255) FOREIGN KEY REFERENCES C(VALUE) NOT NULL, id VARCHAR(255) PRIMARY KEY)
;
CREATE TABLE abc
(A_id VARCHAR(255) FOREIGN KEY REFERENCES A(ID), value DATETIME, CONSTRAINT abc_pkey PRIMARY KEY(A_ID, VALUE))
;