#!/bin/sh

echo "Adding license and copyright related metadata... "

reuse addheader \
    --copyright "Alliander N.V." \
    --year `date +%Y` \
    --license "Apache-2.0" \
    --recursive \
    --skip-unrecognised \
    --merge-copyrights \
    resources/ \
    scripts/ \
    src/ \
    test/ \
    .editorconfig \
    .gitattributes \
    .gitignore \
    CHANGELOG.md \
    CONTRIBUTING.md \
    PROJECT_GOVERNANCE.md \
    project.clj \
    README.md \
    SUPPORT.md \
  | grep -v -e '^Skipped ' \
            -e '^Successfully changed header'

echo "Done."
